controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: position_controllers/GripperActionController

arm_controller:
  ros__parameters:
    joints:
      - base_rotation_joint
      - shoulder_joint
      - wrist_joint
      - forearm_joint
      - elbow_joint
      
    command_interfaces:
      - position
      
    state_interfaces:
      - position
      - velocity
      

gripper_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    goal_tolerance: 0.02
    allow stalling: true
    joint: gripper_joint 
    command_interfaces:
    stall_timeout: 3.0
    stall_velocity_threshold: 0.001