controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: position_controllers/GripperActionController

arm_controller:
  ros__parameters:
    joints:
      - base_rotation_joint
      - shoulder_joint
      - wrist_joint
      - forearm_joint
      - elbow_joint
      
    command_interfaces:
      - position
      
    state_interfaces:
      - position
      - velocity
      
    open_loop_control: true
    allow_partial_joints_goal: false
    
    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 0.5
      
    gains:
      base_rotation_joint: {p: 10.0, i: 0.0, d: 1.0}
      shoulder_joint: {p: 10.0, i: 0.0, d: 1.0}
      wrist_joint: {p: 10.0, i: 0.0, d: 1.0}
      forearm_joint: {p: 10.0, i: 0.0, d: 1.0}
      elbow_joint: {p: 10.0, i: 0.0, d: 1.0}

gripper_controller:
  ros__parameters:
    joint: gripper_joint
    
    command_interfaces:
      - position
      
    state_interfaces:
      - position
      - velocity
    
    action_monitor_rate: 20.0
    goal_tolerance: 0.05
    max_effort: 10.0
    
    gains:
      gripper_joint: {p: 50.0, i: 2.0, d: 5.0}