# Default initial positions for sabse_final_robo_dusra's ros2_control fake system

initial_positions:
  base_rotation_joint: 0
  elbow_joint: 0
  forearm_joint: 0
  gripper_joint: 0
  shoulder_joint: 0
  wrist_joint: 0